---
ReportDefinitions:
  - reportName: billCountReport
    summary: Bill Count Report
    version: 1.0.0
    moduleName: rainmaker-fin
    sourceColumns:
      - name: bill_date
        label: Bill Date
        type: epoch
        source: lba
        total: false
      - name: total_amount
        label: Total Amount
        type: number
        source: lba
        total: true
        rowTotal: true
      - name: bill_count
        label: Bill Count
        type: number
        source: lba
        total: true
        rowTotal: true
    searchParams:
      - name: schema_name
        label: Schema Name
        type: singlevaluelist
        pattern: 'list://jmc:Jammu Municipal Corporation,smc:Srinagar Municipal Corporation'
        source: lba
        isMandatory: true
        searchClause: AND lba.schema_name = $schema_name
    query: >
      SELECT
        lba.bill_date,
        lba.total_amount,
        lba.bill_count
      FROM
        live_bills_all lba
      WHERE
        1=1
    orderby: ORDER By bill_date desc

  - reportName: collectionReport
    summary: Collection Report
    version: 1.0.0
    moduleName: rainmaker-fin
    sourceColumns:
      - name: created_date
        label: Created Date
        type: date
        source: ei
        total: false
      - name: transaction_count
        label: Transaction Count
        type: number
        source: ei
        total: true
        rowTotal: true
      - name: total_amount
        label: Total Amount
        type: number
        source: ei
        total: true
        rowTotal: true
    searchParams:
      - name: fromDate
        label: From Date
        type: epoch
        source: ei
        isMandatory: false
        searchClause: AND ei.createddate >= TO_TIMESTAMP($fromDate / 1000)
      - name: toDate
        label: To Date
        type: epoch
        source: ei
        isMandatory: false
        searchClause: AND ei.createddate <= TO_TIMESTAMP($toDate / 1000)
    query: >
      SELECT
        DATE(ei.createddate) AS created_date,
        COUNT(*) AS transaction_count,
        SUM(ei.amount) AS total_amount
      FROM
        egf_instrument ei
      WHERE
        1=1
    groupby : GROUP BY DATE(ei.createddate)    
    orderby: ORDER BY created_date desc